import { Component, OnInit ,Input} from '@angular/core';

@Component({
  selector: 'app-header-part',
  template:       
  `<div> 
  <div id='heading' class="globalHeadings">
		{{heading}}
		<hr>
	</div>	
  </div>` 
  ,
   // templateUrl : './header-part.component.html'  ,
  styleUrls: ['./header-part.component.css']
})
export class HeaderPartComponent implements OnInit {


  @Input() heading : string; 
  constructor() { 
  }

  ngOnInit() {
      let colorAdjustmentIndex = 30;
      let colorPalletteSize = 5;
      let autoGeneratedStartColor = colorUtils.autoGenerateLightColor();
      let colorPalleteArray=  colorUtils.getRandomColorPallette(autoGeneratedStartColor,colorPalletteSize,colorAdjustmentIndex,colorUtils.add);
      let fontColor = colorPalleteArray[4]
      let backgroundColor = colorPalleteArray[0]

      let formedStyle = "color:"+fontColor+";background-color:"+backgroundColor ;
      document.getElementById('heading').setAttribute("style",formedStyle); 
      
  }

}
